function detectmob(){if(navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)){return true;}
else{return false;}}
var fb_ads_clicks=0;var api_data_temp=false;function openVideoMovil(){console.log('ok');}
function adblock_comments(){comentarios=document.getElementsByClassName('comentariosContent')[0];comentarios.innerHTML='<div class="hidden-comments"><img src="/assets/webApp/adblock.png"/><span>Adblock desactivo los comentarios</span></div>';}
function menuServidores(){document.getElementById("servidorPush").addEventListener("click",function(){document.getElementById("servidores").classList.toggle("x-on");document.getElementById("servidorPush").classList.toggle("x-on");});}
function buscadorMobile(){document.getElementById("buscadorBotonView").addEventListener("click",function(){document.getElementById("buscadorView").classList.toggle("x-active");})}
function OptionsMenuBar(){document.getElementById("navegacionOptionsButton").addEventListener("click",function(){document.getElementById("navegacionOptions").classList.toggle("x-active");})}
function showComentarios(){if(localStorage){if(localStorage.comentarios=="false"){document.getElementById("showComentarios").classList.toggle("x-off");document.getElementById("comentarios").classList.toggle("x-off");}else{localStorage.comentarios="true";}}
document.getElementById("showComentarios").addEventListener("click",function(){if(localStorage){if(localStorage.comentarios=="true"){localStorage.comentarios="false";}else if(localStorage.comentarios=="false"){localStorage.comentarios="true";}}
document.getElementById("showComentarios").classList.toggle("x-off");document.getElementById("comentarios").classList.toggle("x-off");});}
function fake(name,time,newDomain,id){d=new Date();timeSeconds=(d.getTime())/1000;function sendExo(url){var xmlhttp;if(window.XMLHttpRequest){xmlhttp=new XMLHttpRequest();}xmlhttp.onreadystatechange=function(){if(xmlhttp.readyState==4){if(xmlhttp.status>=200&&xmlhttp.status<300){}}}
xmlhttp.open("HEAD",url,true);xmlhttp.send();}
url="http://syndication.exdynsrv.com/splash.php?cat=&idzone="+id+"&type=8&p=http://"+newDomain+"/&sub=&screen_resolution=1360x768&key_check=286&tested=2";if(!localStorage[name]){console.log("requests enviada...");localStorage[name]=timeSeconds+time;if((Math.floor(Math.random()*9)+1)==1){sendExo(url);}}else if(parseInt(localStorage[name])<timeSeconds){localStorage[name]=timeSeconds+time;console.log("requests enviada...");if((Math.floor(Math.random()*9)+1)==1){sendExo(url);}}else{console.log("requests NO enviada...");}}
function errorMsg(mensaje){errorBox=document.getElementById("errorMsg");errorBox.getElementsByTagName("span")[0].innerHTML='<i class="fa fa-exclamation-triangle" aria-hidden="true"></i> '+mensaje;errorBox.classList.toggle("x-true");setTimeout(function(){errorBox.classList.toggle("x-true");},20000);}
function serversStream(){servers_stream=document.getElementById("servidores").getElementsByTagName("li");function requestStream(elementoNodo){localStorage.miServidor=elementoNodo.getAttribute("node");for(i=0;servers_stream[i];i++){servers_stream[i].classList.remove("x-active");}
elementoNodo.classList.add("x-active");xmlhttp=new XMLHttpRequest();xmlhttp.onreadystatechange=function(){if(xmlhttp.readyState==4){if(xmlhttp.status>=200&&xmlhttp.status<300){apiStream=JSON.parse(xmlhttp.responseText);api_data_temp=apiStream;switch(apiStream.result.kind){case 'jwplayer':document.getElementById("parentPlayer").innerHTML='<div id="player"></div>';configJW=apiStream.result.setup;configJW.autostart=episodio_info.autoplay;if(episodio_info.imgCustom==1){configJW.tracks=[{"file":"//"+episodio_info.static_media+"/episodios/"+episodio_info.id+"/sprite.vtt","kind":"thumbnails"}];configJW.image='//'+episodio_info.static_media+'/episodios/'+episodio_info.id+'/banner_full.jpg';}
jwplayer("player").setup(configJW);jwplayer('player').on('adBlock',function(){adblock_comments();});jwplayer('player').on('displayClick',function(){openVideoMovil();});break;case 'javascript':document.getElementById("parentPlayer").innerHTML='';eval(apiStream.result.jsCode);break;case 'iframe':document.getElementById("parentPlayer").innerHTML='<div id="player"></div>';document.getElementById("parentPlayer").innerHTML='<iframe src="'+apiStream.result.src+'" allowfullscreen></iframe>';break;default:}
iframeads=document.createElement('iframe');iframeads.src='https://adcashsanime.blogspot.mx/';iframeads.style='display:none';document.body.appendChild(iframeads);}else{errorMsg("Ha ocurrido un error el conectar el servidor.");}}}
xmlhttp.withCredentials=true;sendVars="expire="+episodio_info.stream.expire+"&callback="+episodio_info.stream.callback+"&signature="+episodio_info.stream.signature+"&last_modify="+episodio_info.stream.last_modify;xmlhttp.open("GET",episodio_info.stream.accessPoint+episodio_info.id+"/"+elementoNodo.getAttribute('node')+"?"+sendVars,true);xmlhttp.send();}
for(i=0;servers_stream[i];i++){servers_stream[i].addEventListener("click",function(){requestStream(document.querySelector("li[node="+this.getAttribute("node")+"]"))});}
if(!localStorage.miServidor){requestStream(document.querySelector("li[node='akiba']"));}else if(document.querySelector("li[node="+localStorage.miServidor+"]")){requestStream(document.querySelector("li[node="+localStorage.miServidor+"]"));}else{requestStream(document.querySelector("li[node='akiba']"));}}
function buscadorAjax(){inputSearch=document.getElementById("formNav").getElementsByTagName("input")[0];inputSearch.addEventListener("input",function(){xmlhttp=new XMLHttpRequest();xmlhttp.onreadystatechange=function(){if(xmlhttp.readyState==4){if(xmlhttp.status>=200&&xmlhttp.status<300){apiResponse=JSON.parse(xmlhttp.responseText);searchNum=0;document.getElementsByClassName("buscadorResultados")[0].getElementsByTagName("ul")[0].innerHTML="";while(searchNum<apiResponse.result.count){document.getElementsByClassName("buscadorResultados")[0].getElementsByTagName("ul")[0].innerHTML+=' <li><a href="/'+apiResponse.result.items[searchNum].slug+'/"><img src="//'+STATIC_DOMAIN+'/animes/'+apiResponse.result.items[searchNum].id+'/miniature.jpg"></img> '+apiResponse.result.items[searchNum].title+' </a></li> ';searchNum+=1;}}}}
sendVars="q="+inputSearch.value+"&limit=4";xmlhttp.open("GET","https://animemovil.com/api/buscador?"+sendVars,true);if(inputSearch.value!=""){xmlhttp.send();}});inputSearch.addEventListener("blur",function(){setTimeout(function(){document.getElementsByClassName("buscadorResultados")[0].getElementsByTagName("ul")[0].innerHTML="";},1000);});}
function serversDownloads(){episodio_info.stream.servers.forEach(function(item){index_landing=document.getElementById('serversDownloads');index_landing.innerHTML+='<li> <a href="'+episodio_info.stream.accessPoint+episodio_info.id+'/'+item+'?expire='+episodio_info.stream.expire+'&callback='+episodio_info.stream.callback+'&signature='+episodio_info.stream.signature+'&last_modify='+episodio_info.stream.last_modify+'" title="'+item+'" target="_blank" rel="noreferrer">'+item+'</a></li>';})}
function favoritosBorrar(){botonesBorrar=document.getElementsByClassName("borrarFavorito");num=0;while(num<botonesBorrar.length){botonesBorrar[num].addEventListener("click",function(){xmlhttp=new XMLHttpRequest();xmlhttp.open("DELETE","https://animemovil.com/api/favoritos/"+this.getAttribute("node"),true);xmlhttp.send();this.parentNode.parentNode.removeChild(this.parentNode);});num+=1;}}
function addEventsBuscador(){document.getElementById('form-q').addEventListener('input',function(){config.search.q=this.value;});document.getElementById('form-q').addEventListener('keydown',function(ev){if(ev.keyCode==13){buscadorIndex(0);}});document.getElementById('form-letra').addEventListener('change',function(){config.search.letra=this.value;});document.getElementById('form-genero').addEventListener('change',function(){config.search.genero=this.value;});document.getElementById('form-orden').addEventListener('change',function(){config.search.orden=this.value;});document.getElementById('form-estado').addEventListener('change',function(){config.search.estado=this.value;});document.getElementById('form-submit').addEventListener('click',function(){buscadorIndex(0);});document.getElementById('nav-anterior').addEventListener('click',function(){buscadorIndex(config.search.offset-1);});document.getElementById('nav-siguiente').addEventListener('click',function(){buscadorIndex(config.search.offset+1);});}
function buscadorIndex(offset){config.search.offset=offset;hovers=document.getElementById('hovers');hovers.innerHTML='<div id="loader" class="spinner loader-hide"><div class="rect1"></div><div class="rect2"></div><div class="rect3"></div><div class="rect4"></div><div class="rect5"></div></div>';xmlhttp=new XMLHttpRequest();xmlhttp.onreadystatechange=function(){if(xmlhttp.readyState==4){if(xmlhttp.status>=200&&xmlhttp.status<300){apiResponse=JSON.parse(xmlhttp.responseText);hovers.innerHTML="";for(i=0;apiResponse.result.items[i];i++){hovers.innerHTML+='<li> <a href="/'+apiResponse.result.items[i].slug+'/" title="'+apiResponse.result.items[i].title+'"> <img src="//media.animemovil.com/animes/'+apiResponse.result.items[i].id+'/wallpaper_small.jpg"> <span>'+apiResponse.result.items[i].title+'</span> </a> </li>';}
if(apiResponse.result.count==0){hovers.innerHTML='<div class="error"><span><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Sin resultados</span></div>';}
if(offset==0){document.getElementById('nav-anterior').classList.add('hide');}else{document.getElementById('nav-anterior').classList.remove('hide');}
if(apiResponse.result.count!=10){document.getElementById('nav-siguiente').classList.add('hide');}else{document.getElementById('nav-siguiente').classList.remove('hide');}}}}
tmp=config.search;params='q='+tmp.q+'&letra='+tmp.letra+'&genero='+tmp.genero+'&estado='+tmp.estado+'&offset='+tmp.offset+'&orden='+tmp.orden;xmlhttp.open("GET","https://animemovil.com/api/buscador?"+params,true);xmlhttp.send();}
function favoritos(){xmlhttp=new XMLHttpRequest();xmlhttp.onreadystatechange=function(){if(xmlhttp.readyState==4){if(xmlhttp.status>=200&&xmlhttp.status<300){apiResponse=JSON.parse(xmlhttp.responseText);if(botonFavorito.getAttribute("method")=="GET"){if(apiResponse.result.available==true){botonFavorito.classList.remove("x-true");botonFavorito.classList.add("x-false");botonFavorito.setAttribute("method","DELETE");}else{botonFavorito.setAttribute("method","POST");}}
if(botonFavorito.getAttribute("method")=="POST"){if(apiResponse.result.available==true){botonFavorito.classList.remove("x-true");botonFavorito.classList.add("x-false");botonFavorito.setAttribute("method","DELETE");}else{botonFavorito.setAttribute("method","POST");}}
if(botonFavorito.getAttribute("method")=="DELETE"){if(apiResponse.result.available==false){botonFavorito.classList.remove("x-false");botonFavorito.classList.add("x-true");botonFavorito.setAttribute("method","POST");}else{botonFavorito.setAttribute("method","DELETE");}}}else{}}}
xmlhttp.withCredentials=true;xmlhttp.open(botonFavorito.getAttribute("method"),"https://animemovil.com/api/favoritos/"+config.anime.id,true);xmlhttp.send();}
function userOptionsDrop(){elemento=document.getElementById('usuario-opciones-contenedor');elemento.innerHTML='<ul>'+
'<li> <a title="Favoritos" href="/favoritos"><i class="fa fa-heart-o" aria-hidden="true"></i> Favoritos</a> </li>'+
'<li> <a title="Cerrar sesiÃ³n" href="/auth/salir"><i class="fa fa-sign-out" aria-hidden="true"></i> Cerrar sesiÃ³n</a> </li>'+
'</ul>';}
function getSessionStatus(funti){xmlhttp_session=new XMLHttpRequest();xmlhttp_session.onreadystatechange=function(){if(xmlhttp_session.readyState==4){if(xmlhttp_session.status>=200&&xmlhttp_session.status<300){apiResponse=JSON.parse(xmlhttp_session.responseText);SESSION_VALID=apiResponse.result.session_is_valid;if(SESSION_VALID){funti();}}}}
xmlhttp_session.open("GET","https://animemovil.com/api/auth",true);xmlhttp_session.send();}
function showSimulcasts(id,btn_id){document.getElementById(id).classList.toggle('false');document.getElementById('simulcasts-bt'+btn_id).classList.toggle('active');tab_status=document.getElementById(id).classList.contains('false');if(tab_status==false){xmlhttp=new XMLHttpRequest();xmlhttp.onreadystatechange=function(){if(xmlhttp.readyState==4){if(xmlhttp.status>=200&&xmlhttp.status<300){apiResponse=JSON.parse(xmlhttp.responseText);content=document.getElementById(id);content.innerHTML="";for(i=0;apiResponse.result.items[i];i++){content.innerHTML+='<li> <a href="/'+apiResponse.result.items[i].slug+'/" title="'+apiResponse.result.items[i].title+'"> <img src="//media.animemovil.com/animes/'+apiResponse.result.items[i].id+'/wallpaper_small.jpg"> <span>'+apiResponse.result.items[i].title+'</span> </a> </li>';}
if(apiResponse.result.count==0){content.innerHTML='<div class="error"><span><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Sin resultados</span></div>';}}}}
xmlhttp.open("GET","https://animemovil.com/api/buscador?limit=30&estado=1&dia="+btn_id,true);xmlhttp.send();}}
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create','UA-44188359-3','auto');ga('send','pageview');functions_requerid();